// Version and build number header for an2plugin.xpl.
// Generated by gen_make.sh, build number is auto-incremented on build.
//

#ifndef __BuildNum_h__
#define __BuildNum_h__

#define Version1	1
#define Version2	0
#define Version3	0
#define BuildNum	1

#endif//__BuildNum_h__

